workflows:
  ios-release:
    name: iOS simulator build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get flutter dependencieris
        script: flutter pub get
      - name: build ios app simultor
        script: flutter build ios --simulator --debug
    artifacts:
      - build/ios/iphoneos/*.app
