workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: stable
      xcode: 16.3
      cocoapods: 1.16.2
      vars:
        BUNDLE_ID: "com.palopoapp.splitdo"
    scripts:
      - name: Clean and get dependencies
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update
          cd ..
      - name: Activate FlutterFire CLI (se serve)
        script: |
          dart pub global activate flutterfire_cli
          export PATH="$PATH":"$HOME/.pub-cache/bin"
      # Se vuoi usare flutterfire configure, aggiungi qui:
      # - flutterfire configure --project=YOUR_FIREBASE_PROJECT_ID
      - name: Build iOS (no code signing)
        script: |
          flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/**/*.app
