workflows:
  ios-build:
    name: iOS Build with Privacy Bundle Fix
    environment:
      flutter: "3.22.1"
      xcode: latest

    scripts:
      - name: Clean Flutter project
        script: |
          flutter clean
          flutter pub get

      - name: Clean iOS build and CocoaPods
        script: |
          cd ios
          rm -rf Pods
          rm -rf build
          rm -f Podfile.lock
          pod cache clean --all
          pod repo update
          pod install --repo-update
          cd ..

      - name: Build iOS App (no codesign)
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.app
