workflows:
  ios-release:
    name: iOS Release
    environment:
      flutter: stable
      xcode: 16.3
      cocoapods: 1.16.2
    scripts:
      - name: Clean, update, and prepare project
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock
          flutter pub get
      - name: Update CocoaPods repo and cache
        script: |
          cd ios
          pod cache clean --all
          pod install --repo-update
          cd ..
      - name: Build iOS (no codesign)
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/ipa/*.ipa
      - build/**/outputs/**/*.aab
