name: splitdo_app
description: A new Flutter project.

# La versione dell'applicazione seguita da +numero build
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  app_links: ^6.2.0
  shared_preferences: ^2.2.3
  provider: ^6.1.5
  url_launcher: ^6.3.0
  share_plus: ^7.2.2
  firebase_messaging: ^15.2.7
  flutter_local_notifications: ^18.0.1
  flutter_slidable: ^3.1.2
  google_mobile_ads: ^5.3.1
  connectivity_plus: ^6.1.4
  webview_flutter_wkwebview: ^3.12.0
  url_launcher_ios: ^6.3.1
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/italian_words.txt
