name: splitdo_app
description: "A Flutter app for collaborative shopping lists and expense splitting."
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # le versioni qui sotto sono fra loro compatibili
  firebase_core: "^3.7.0"
  firebase_auth: "^5.5.3"
  cloud_firestore: "^5.6.7"
  app_links: "^6.3.2"
  shared_preferences: "^2.0.0"
  provider: "^6.0.0"
  url_launcher: "^6.1.10"
  share_plus: "^11.0.0"
  firebase_messaging: "^15.2.5"
  flutter_local_notifications: "^18.0.0"
  flutter_slidable: "^4.0.0"
  google_mobile_ads: "6.0.0"
  connectivity_plus: "^4.0.2"
    

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/italian_words.txt
